version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - '5436:5432'
    networks:
        - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8889:80"
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge